// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_int int32

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgo_runtime_cgocallback runtime.cgocallback
func _cgo_runtime_cgocallback(unsafe.Pointer, unsafe.Pointer, uintptr, uintptr)

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, ...interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_import_static _cgo_3f17e2e00548_Cfunc_addByC
//go:linkname __cgofn__cgo_3f17e2e00548_Cfunc_addByC _cgo_3f17e2e00548_Cfunc_addByC
var __cgofn__cgo_3f17e2e00548_Cfunc_addByC byte
var _cgo_3f17e2e00548_Cfunc_addByC = unsafe.Pointer(&__cgofn__cgo_3f17e2e00548_Cfunc_addByC)

//go:cgo_unsafe_args
func _Cfunc_addByC(p0 _Ctype_int, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_3f17e2e00548_Cfunc_addByC, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_3f17e2e00548_Cfunc_addByGo
//go:linkname __cgofn__cgo_3f17e2e00548_Cfunc_addByGo _cgo_3f17e2e00548_Cfunc_addByGo
var __cgofn__cgo_3f17e2e00548_Cfunc_addByGo byte
var _cgo_3f17e2e00548_Cfunc_addByGo = unsafe.Pointer(&__cgofn__cgo_3f17e2e00548_Cfunc_addByGo)

//go:cgo_unsafe_args
func _Cfunc_addByGo(p0 _Ctype_int, p1 _Ctype_int) (r1 _Ctype_int) {
	_cgo_runtime_cgocall(_cgo_3f17e2e00548_Cfunc_addByGo, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_export_dynamic addByGo
//go:linkname _cgoexp_3f17e2e00548_addByGo _cgoexp_3f17e2e00548_addByGo
//go:cgo_export_static _cgoexp_3f17e2e00548_addByGo
//go:nosplit
//go:norace
func _cgoexp_3f17e2e00548_addByGo(a unsafe.Pointer, n int32, ctxt uintptr) {
	fn := _cgoexpwrap_3f17e2e00548_addByGo
	_cgo_runtime_cgocallback(**(**unsafe.Pointer)(unsafe.Pointer(&fn)), a, uintptr(n), ctxt);
}

func _cgoexpwrap_3f17e2e00548_addByGo(p0 _Ctype_int, p1 _Ctype_int) (r0 _Ctype_int) {
	return addByGo(p0, p1)
}
