// Code generated by cmd/cgo; DO NOT EDIT.

//line add.go:1:1
package main

import _ "unsafe"

//export addByGo
func addByGo(a, b  /*line :6:19*/_Ctype_int /*line :6:24*/)  /*line :6:26*/_Ctype_int /*line :6:31*/ {
	return a + b
}
