// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

//int sum(int a, int b);
import _ "unsafe"
import "fmt"

//export sum
func sum(a, b  /*line :8:15*/_Ctype_int /*line :8:20*/)  /*line :8:22*/_Ctype_int /*line :8:27*/ {
	return a + b
}

func main() {
	// run `go build -buildmode=c-archive -o sum.a main.go`
	// to generate header(sum.h) and library(sum.a) files
	// run `go tool cgo main.go` to generate intermediate files
	fmt.Println(( /*line :16:14*/_Cfunc_sum /*line :16:18*/)(1, 1))
}
